---

- name: Update backup folder list
  blockinfile:
    path: "{{ borgbackup_home }}/config/patterns"
    marker: "# {mark} ANSIBLE MANAGED {{ service }} BLOCK"
    create: no
    block: |
      {% for path in paths %}
      R {{ path }}
      {% endfor %}
    owner: "{{ borgbackup_user }}"
    group: "{{ borgbackup_user }}"
    mode: "0600"
  when: paths is defined

- name: Install backup service
  template:
    src: borgbackup-tasks@.service.j2
    dest: /etc/systemd/system/borgbackup-tasks@{{ service|mandatory }}.service
    mode: "0644"
  when: backup_command is defined
  notify: Reload systemd

- name: Enable backup service
  systemd:
    daemon_reload: yes
    name: borgbackup-tasks@{{ service|mandatory }}
    enabled: yes
  when: backup_command is defined
