---

- name: Install borgbackup
  hosts: all

  pre_tasks:
    - name: Create backup user
      user:
        name: "{{ borgbackup_user }}"

  roles:
    - apollo13.borgbackup

- name: Configure clients
  hosts: client

  tasks:

    - name: Configure working backup
      include_role:
        name: apollo13.borgbackup
        tasks_from: configure.yml
      vars:
        service: test_working
        backup_user: root
        backup_command: /bin/true
        paths:
          - /etc
      when: '"system" in inventory_hostname'

    - name: Configure failing backup
      include_role:
        name: apollo13.borgbackup
        tasks_from: configure.yml
      vars:
        service: test_failing
        backup_user: root
        backup_command: /bin/false
        paths:
          - /home
      when: '"upstream" in inventory_hostname'
